# Generated by Django 6.0.7 on 2026-08-18 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditor", "0002_repository_student_event_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BiWeeklyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Bi-Weekly Report", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Locked", "Locked"),
                            ("Reviewed", "Reviewed"),
                            ("Changes Requested", "Changes Requested"),
                        ],
                        default="Draft",
                        max_length=50,
                    ),
                ),
                ("meeting_date", models.DateField(blank=True, null=True)),
                (
                    "milestones",
                    models.JSONField(
                        blank=True,
                        help_text="List of milestone objects with status",
                        null=True,
                    ),
                ),
                ("text_design", models.TextField(blank=True, null=True)),
                ("text_prototype", models.TextField(blank=True, null=True)),
                ("text_dissertation", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bi_weekly_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyGitAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("day_of_week", models.CharField(max_length=20)),
                ("raw_diff", models.TextField(blank=True, null=True)),
                ("loc_added", models.IntegerField(default=0)),
                ("loc_deleted", models.IntegerField(default=0)),
                ("llm_summary", models.TextField(blank=True, null=True)),
                ("diff_snippet", models.TextField(blank=True, null=True)),
                (
                    "ai_status",
                    models.CharField(
                        choices=[
                            ("green", "Green"),
                            ("yellow", "Yellow"),
                            ("red", "Red"),
                        ],
                        default="green",
                        max_length=10,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_audits",
                        to="auditor.biweeklyreport",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="EvidenceImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="evidence_images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_images",
                        to="auditor.biweeklyreport",
                    ),
                ),
            ],
        ),
    ]
