# Generated by Django 6.0.7 on 2026-08-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditor", "0003_biweeklyreport_dailygitaudit_evidenceimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="biweeklyreport",
            name="supervisor_feedback",
            field=models.TextField(blank=True, null=True),
        ),
    ]
