# Generated by Django 6.0.7 on 2026-08-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditor", "0004_biweeklyreport_supervisor_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="biweeklyreport",
            name="text_agenda",
            field=models.TextField(blank=True, null=True),
        ),
    ]
