# Generated by Django 6.0.7 on 2026-08-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditor", "0005_biweeklyreport_text_agenda"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="access_token",
            field=models.CharField(
                blank=True,
                help_text="该学生专属的 GitLab 访问令牌",
                max_length=255,
                null=True,
            ),
        ),
    ]
