# Generated by Django 6.0.7 on 2026-08-19 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditor", "0006_repository_access_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="biweeklyreport",
            name="text_completed",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="evidenceimage",
            name="image",
            field=models.FileField(upload_to="evidence_images/"),
        ),
        migrations.AlterField(
            model_name="repository",
            name="access_token",
            field=models.CharField(
                blank=True,
                help_text="The student’s personal GitLab access token",
                max_length=255,
                null=True,
            ),
        ),
    ]
