# Generated by Django 6.0.7 on 2026-07-30 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommitTelemetry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commit_hash", models.CharField(max_length=40, unique=True)),
                ("author_name", models.CharField(max_length=100)),
                ("commit_message", models.TextField()),
                ("raw_diff", models.TextField()),
                ("committed_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="AuditResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=10)),
                ("score", models.IntegerField()),
                ("justification", models.TextField()),
                (
                    "manual_override_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "telemetry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="poc.committelemetry",
                    ),
                ),
            ],
        ),
    ]
